config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :activities, only:[ :index, :show ]
  resources :restaurants, only:[:index, :show]
  resources :reviews, only: [:create, :destroy]
  resources :bookings, only: [:index,:show,:update,:destroy]

  get "category", to: "pages#category", as: :category
  patch "add_restaurant", to: "bookings#add_restaurant", as: :add_restaurant
  patch "add_activity", to: "bookings#add_activity", as: :add_activity

  post "activity_redirect_booking", to: "bookings#activity_redirect_booking", as: :activity_redirect_booking
  post "restaurant_redirect_booking", to: "bookings#restaurant_redirect_booking", as: :restaurant_redirect_booking
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :activity, optional: true
  belongs_to :restaurant, optional: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: [:show,:destroy,:update]

  def index
    @bookings = Booking.all
  end


  def show
    @booking = Booking.find(params[:id])

    @markers = [ @booking.restaurant, @booking.activity].map do |thing|
      next if thing.nil?
      {
        lat: thing.latitude,
        lng: thing.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { thing: thing })
      }
    end
    @markers.reject!(&:nil?)
  end

  def restaurant_redirect_booking
    @booking = Booking.new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @booking.restaurant = @restaurant
    @booking.user = current_user
    @booking.save
    redirect_to activities_path
  end
  def activity_redirect_booking
    @booking = Booking.new
    @activity = Activity.find(params[:activity_id])
    @booking.activity = @activity
    @booking.user = current_user
    @booking.save
    redirect_to restaurants_path
  end

  def add_restaurant
    booking = Booking.find(params[:booking_id])
    restaurant = Restaurant.find(params[:restaurant_id])
    booking.update(restaurant_id: restaurant.id)
    redirect_to bookings_path
  end

  def add_activity
    booking = Booking.find(params[:booking_id])
    activity = Activity.find(params[:activity_id])
    booking.update(activity_id: activity.id)
    redirect_to bookings_path
  end

  def update
    @booking.update(confirmed: true, date: params[:booking][:date])
    redirect_to bookings_path
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def find_booking
    @booking = Booking.find(params[:id])
  end

end

app/views/bookings/_info_window.html.erb
<div>
  <h4><%= link_to thing.name, send("#{thing.class.to_s.downcase}_path", thing) %></h4>
  <p><%= thing.address %></p>
</div>

app/views/bookings/index.html.erb
<div class="container text-align-center"> <!-- container for whole page -->
<h1 class="text-center mt-4 mb-5">Your date plans</h1>


  <% @bookings.order(date: :desc).each do |booking| %>


    <%= link_to booking_path(booking) do %>
    <div class="booking-plan">
      <div class="booking-index-function">
        <% if booking.date %>
          <p class="text-center"><%= booking.date%></p>
        <% end %>

      <!-- Booking confirm -->
        <% if booking.confirmed %>
          <p class="text-center">Booking Confirmed <i class="fas fa-calendar-check"></i></p>
         <% else %>
          <p class="text-center">Not yet confirmed <i class="fas fa-exclamation-triangle"></i></p>
        <% end %>
      </div>


      <div class="bookings-index-content">

        <!-- Activity -->
        <div class="booking-index-activity">
          <% if booking.activity %>
            <%= booking.activity.name %>
            <%= cl_image_tag booking.activity.photo.key, height: 200, width: 280, class: "booking-cards-sm" %>
          <% else %>
            <div class="index-blank-activity">
              <p>No activity chosen yet</p>
            </div>
          <% end %>
        </div>

       <!-- Restaurant -->
        <div class="booking-index-resto">
          <% if booking.restaurant %>
            <%= booking.restaurant.name %>
            <%= cl_image_tag booking.restaurant.photo.key, height: 200, width: 280, class: "booking-cards-sm" %>
          <% else %>
            <div class="index-blank-restaurant">
              <p>No restaurant chosen yet</p>
            </div>

          <% end %>
        </div>
      </div>
      <!-- trash should be outside of the each -->
      <% end %>


     <i class="fas fa-trash trash" id="sweet-alert-demo"></i>
        <%= link_to booking_path(booking), method: :delete, class: 'd-none target' do %>
        <% end %>
        </div>

  <% end %>



</div><!--  div for whole container -->

app/views/bookings/show.html.erb
<div class="container">
  <h1 class="text-center m-4">Your date plan.</h1>

    <div class="boooking-activity-restaurant">
      <!-- activity card -->
      <div class="card-booking-activity">
        <% if @booking.activity_id %>
        <%= link_to activity_path(@booking.activity) do %>
          <%= cl_image_tag @booking.activity.photo.key, class: "booking-activity-image", height: 250, width: 380 %>
        <% end %>
        <div class="booking-activity-info">
          <h5>Activity : <%= @booking.activity.name %></h5>
          <p>Address : <%= @booking.activity.address %></p>
          <p>Open Hours : <%= @booking.activity.open_hour %></p>
          <p>Phone Number : <%= @booking.activity.phone_number %></p>
        </div>
        <% else %>
            <%= link_to activities_path do %>
              <!-- <img src="https://res.cloudinary.com/dhhorrhuq/image/upload/v1583946934/shawn-ang-nmpW_WwwVSc-unsplash_j7d6nv.jpg" alt="Italian Trulli" class="blank-choice-resto"> -->
              <div class="blank-choice-activity">
                <p>Click to choose your activity</p>
              </div>
            <% end %>
        <% end %>

      </div>


      <!-- booking card -->
      <div class="card-booking-restaurant">
         <% if @booking.restaurant_id %>
          <%= link_to restaurant_path(@booking.restaurant) do %>
              <%= cl_image_tag @booking.restaurant.photo.key, height: 250, width: 380 %>
            <% end %>
            <div class="booking-restaurant-info">
              <h5>Restaurant : <%= @booking.restaurant.name %></h5>
              <p>Address : <%= @booking.restaurant.address %></p>
              <p>Open Hours : <%= @booking.restaurant.open_hour %></p>
              <p>Phone Number : <%= @booking.restaurant.phone_number %></p>
            </div>

          <% else %>
            <%= link_to restaurants_path do %>
              <!-- <img src="https://res.cloudinary.com/dhhorrhuq/image/upload/v1583946934/shawn-ang-nmpW_WwwVSc-unsplash_j7d6nv.jpg" alt="test_2_mondxb.png" class="blank-choice-resto">
               --><div class="blank-choice-resto">
                <p>Click to choose your restaurant</p>
               </div>
            <% end %>
        <% end %>
      </div>

      <div class="booking-confirm">
        <% if @booking.confirmed %>
          <p>Plans confirmed for: </p>
          <h5><%= @booking.date %></h5>
          <p class="mt-5">Estimated cost of your date:</p>
          <h5>Between £<%= "#{(@booking.activity&.minimum_price || 0) + (@booking.restaurant&.minimum_price || 0)} - #{(@booking.activity&.price || 0) + (@booking.restaurant&.price || 0)}" %></h5>
        <% else %>
          <p>Estimated cost of your date:</p>
          <h5>Between £<%= "#{(@booking.activity&.minimum_price || 0) + (@booking.restaurant&.minimum_price || 0)} - #{(@booking.activity&.price || 0) + (@booking.restaurant&.price || 0)}" %></h5>

         <%= simple_form_for @booking do |f| %>
          <%= f.input :date, as: :string, input_html: { value: Date.today, min: Date.today, class: "datepicker"} %>
          <%= f.submit "  Confirm  ", class: 'btn btn-dark btn-lg active mb-4 p-12 active toggle'   %>
          <% end %>
        <% end %>
      </div>
    </div><!--  this div for grid -->

  <div id="map" class="mt-5 map-booking-show"
      style="height: 400px !important; width: 900px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      data-routes="<%= true if @markers.length > 1 %>">
  </div>


</div>