config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :activities, only:[ :index, :show ]
  resources :restaurants, only:[:index, :show]
  resources :reviews, only: [:create, :destroy]
  resources :bookings, only: [:index,:show,:update,:destroy]

  get "category", to: "pages#category", as: :category
  patch "add_restaurant", to: "bookings#add_restaurant", as: :add_restaurant
  patch "add_activity", to: "bookings#add_activity", as: :add_activity

  post "activity_redirect_booking", to: "bookings#activity_redirect_booking", as: :activity_redirect_booking
  post "restaurant_redirect_booking", to: "bookings#restaurant_redirect_booking", as: :restaurant_redirect_booking
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_activity_modal.html.erb
<button type="button" class="btn btn-dark" data-toggle="modal" data-target="#exampleModalLong">
  Add to plan
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">

        <h5 class="modal-title" id="exampleModalLongTitle">Add to existing plan</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <% current_user.bookings.where(activity: nil).where.not(confirmed: true).each do |booking| %>
            <div class="d-flex justify-content-between b-card-item">

              <div style="flex: 1" class="b-name ml-4">
               <%= booking.restaurant.name %>
              </div>
               <%= cl_image_tag booking.restaurant.photo.key,class: "b-photo", height: 100, width: 150 %>
               <%= link_to "Add to plan", add_activity_path(booking_id: booking.id, activity_id: @activity.id), method: :patch, class: 'small-booking-button' %>
            </div>
            <hr class="mb-4 mt-4">
          <% end %>

        <div class="text-center">
          <h5>OR</h5>
          <br>
          <button type="button" class="btn btn-dark "><%= link_to "Match with a restaurant",  activity_redirect_booking_path(activity_id: @activity.id), method: :post %></button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Horizontal line / divider -->
<hr>

<!-- Footer -->
<footer class="footer-distributed font-small mdb-color pt-4">

  <!-- Footer Links -->
  <div class="container text-center text-md-left">

    <!-- Footer links -->
    <div class="row text-center text-md-left mt-3 pb-3">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
        <h6 class="text-uppercase mb-4 font-weight-bold">Dating Guru</h6>
        <p>Dating guru makes your life simple! Plan your events and food gathering in a snap! The best app to organize your fun stuff...</p>
      </div>
      <!-- Grid column -->

      <hr class="w-100 clearfix d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
        <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
        <p>
          <%= link_to "Home", root_path, class: "footer-link" %>
        </p>

        <p>
          <%= link_to "Restaurants", restaurants_path, class: "footer-link" %>
        </p>
        <p>
          <%= link_to "Activities", activities_path, class: "footer-link" %>
        </p>
        <p>
          <%= link_to "Dating Plan", bookings_path, class: "footer-link" %>
        </p>

      </div>
      <!-- Grid column -->

      <hr class="w-100 clearfix d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
        <h6 class="text-uppercase mb-4 font-weight-bold">DG Developers</h6>
        <p>Akane Fukui</p>
        <p>Ingrid Cheng</p>
        <p>Tony Huynh</p>
        <p>Kenneth Melchor</p>
      </div>

      <!-- Grid column -->
      <hr class="w-100 clearfix d-md-none">

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
        <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
        <p><i class="fas fa-home mr-3"></i> London, E1 1XW, UK</p>
        <p><i class="fas fa-envelope mr-2"></i><a href="info@dating-guru.site"> info@dating-guru.site</a></p>
        <p><i class="fas fa-phone mr-3"></i> + 44 234 567 88</p>
        <p><i class="fas fa-print mr-3"></i> + 44 234 567 89</p>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Footer links -->

    <hr>

    <!-- Grid row -->
    <div class="row d-flex align-items-center">

      <!-- Grid column -->
      <div class="col-md-7 col-lg-8">

        <!--Copyright-->
        <p class="text-center text-md-left">© 2020 Copyright:
          <a href="https://dating-guru.site/">
            <strong> dating-guru.site</strong>
          </a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-5 col-lg-4 ml-lg-0">

        <!-- Social buttons -->
        <div class="text-center text-md-right">
          <ul class="list-unstyled list-inline">
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-2x fa-facebook-f"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-2x fa-twitter"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-2x fa-google-plus-g"></i>
              </a>
            </li>

          </ul>
        </div>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

</footer>
<!-- Footer -->

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>

<div class="navbar navbar-expand-sm navbar-lewagon" <%= 'style=position:absolute;background:rgba(26,23,23,0)' if params[:action] == 'home' %>>
  <%= link_to root_path, class: "navbar-brand navbar-logo" do %>
    <%= image_tag "heartlogo.png"%>
  <% end %>
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <%= link_to "Activities", activities_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Restaurants", restaurants_path, class: "nav-link" %>
      </li>
    </ul>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Dating Plans", bookings_path, class: "nav-link" %>
      </li>

      <li class="nav-item dropdown">
        <% if current_user.profile_photo.attached?%>
        <%= cl_image_tag current_user.profile_photo.key , class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
        <%= image_tag "nouser.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right dropdown-items" id="dropdown-text" aria-labelledby="navbarDropdown">
          <%= link_to "Settings", "#", class: "dropdown-item", style:'color:black' %>
          <%= link_to "Edit", edit_user_registration_path, class: "dropdown-item", style:'color:black' %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item", style:'color:black' %>
        </div>
      </li>
    </ul>
  </div>
</div>
<!-- repetition -->
<% else %>
<div class="navbar navbar-expand-sm navbar-lewagon" <%= 'style=position:absolute;background:rgba(26,23,23,0.4)' if params[:action] == 'home' %>>
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "heartlogo.png" %>
  <% end %>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Activities", activities_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Restaurants", restaurants_path, class: "nav-link" %>
      </li>
    </ul>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Dating Plan", bookings_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Login", user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>
<% end %>

app/views/shared/_restaurant_modal.html.erb
<button type="button" class="btn btn-dark" data-toggle="modal" data-target="#exampleModalLong">
  Add to plan
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">

        <h5 class="modal-title" id="exampleModalLongTitle">Add to existing plan</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <% current_user.bookings.where(restaurant: nil).where.not(confirmed: true).each do |booking| %>
          <div class="d-flex justify-content-between b-card-item">

            <div style="flex: 1" class="b-name ml-4">
              <%= booking.activity.name %>
            </div>
           <%= cl_image_tag booking.activity.photo.key,class: "b-photo", height: 100, width: 150 %>
           <%= link_to "Add to plan", add_restaurant_path(booking_id: booking.id, restaurant_id: @restaurant), method: :patch, class: 'small-booking-button' %>
          </div>
          <hr class="mb-4 mt-4">
        <% end %>

        <div class="text-center">
          <h5>OR</h5>
          <br>
          <button type="button" class="btn btn-dark "><%= link_to "Match with an activity", restaurant_redirect_booking_path(restaurant_id: @restaurant.id), method: :post%></button>
        </div>
      </div>
    </div>
  </div>
</div>