config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :activities, only:[ :index, :show ]
  resources :restaurants, only:[:index, :show]
  resources :reviews, only: [:create, :destroy]
  resources :bookings, only: [:index,:show,:update,:destroy]

  get "category", to: "pages#category", as: :category
  patch "add_restaurant", to: "bookings#add_restaurant", as: :add_restaurant
  patch "add_activity", to: "bookings#add_activity", as: :add_activity

  post "activity_redirect_booking", to: "bookings#activity_redirect_booking", as: :activity_redirect_booking
  post "restaurant_redirect_booking", to: "bookings#restaurant_redirect_booking", as: :restaurant_redirect_booking
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews
  has_many :bookings
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    if params[:category]
      @restaurants = Restaurant.where(category: params[:category]).geocoded
      @markers = @restaurants.map do |restaurant|
        {
          lat: restaurant.latitude,
          lng: restaurant.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { restaurant: restaurant })
        }
      end

    else
      @restaurants = Restaurant.geocoded

      @markers = @restaurants.map do |restaurant|
        {
          lat: restaurant.latitude,
          lng: restaurant.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { restaurant: restaurant })
        }
      end
    end
  end


  def show
    @restaurant = Restaurant.find(params[:id])
    @markers =
      {
        lat: @restaurant.latitude,
        lng: @restaurant.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { restaurant: @restaurant })
      }
    @review = Review.new
  end
end

app/views/restaurants/_info_window.html.erb
<div>
  <h4 id="map-activity-name"><%= link_to restaurant.name, restaurant_path(restaurant) %></h4>
  <p><%= restaurant.address %></p>
</div>

app/views/restaurants/_restaurants-carousel.html.erb
<form class="restaurant-category" action="/restaurants" method="GET">
          <input class="restaurant-card-pic" type="image" name="All" src="https://res.cloudinary.com/dhhorrhuq/image/upload/v1583496782/category_resto_all_cvbqtn.jpg" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "All", restaurants_path %>
        </form>

        <form class="restaurant-category" action="/restaurants" method="GET">
          <%= hidden_field_tag :category, "Italian"  %>
          <input class="restaurant-card-pic" type="image" name="Italian" src="https://res.cloudinary.com/dhhorrhuq/image/upload/v1583496400/category_resto_italian_fhgvbn.jpg" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Italian",restaurants_path(category: "Italian") %>
        </form>

        <form class="restaurant-category" action="/restaurants" method="GET">
          <%= hidden_field_tag :category, "Japanese"  %>
          <input class="restaurant-card-pic" type="image"  name="Japanese" src="https://res.cloudinary.com/dhhorrhuq/image/upload/v1583496400/category-resto-japanese_qjxudr.jpg" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Japanese", restaurants_path(category: "Japanese") %>
        </form>

        <form class="restaurant-category" action="/restaurants" method="GET">
          <%= hidden_field_tag :category, "Seafood"  %>
          <input class="restaurant-card-pic" type="image" name="Seafood" src="https://res.cloudinary.com/dhhorrhuq/image/upload/v1583496770/category_resto_seafoodrevised_orpu7e.jpg" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Seafood", restaurants_path(category: "Seafood") %>
        </form>

        <form class="restaurant-category" action="/restaurants" method="GET">
          <%= hidden_field_tag :category, "Vegan"  %>
          <input class="restaurant-card-pic" type="image" name="Vegan" src="https://res.cloudinary.com/dhhorrhuq/image/upload/v1583496407/category_resto_vegan_boevbv.jpg" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Vegan", restaurants_path(category: "Vegan") %>
        </form>

        <form class="restaurant-category" action="/restaurants" method="GET">
          <input class="restaurant-card-pic" type="image" name="All" src="https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1867&q=80" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Vietnamese", restaurants_path %>
        </form>

        <form class="restaurant-category" action="/restaurants" method="GET">
          <%= hidden_field_tag :category, "Italian"  %>
          <input class="restaurant-card-pic" type="image" name="Italian" src="https://images.unsplash.com/photo-1551782450-a2132b4ba21d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Burgers",restaurants_path(category: "Italian") %>
        </form>

        <form class="restaurant-category" action="/restaurants" method="GET">
          <%= hidden_field_tag :category, "Japanese"  %>
          <input class="restaurant-card-pic" type="image"  name="Japanese" src="https://images.unsplash.com/photo-1567337710282-00832b415979?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2688&q=80" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Indian", restaurants_path(category: "Japanese") %>
        </form>

        <form class="restaurant-category" action="/restaurants" method="GET">
          <%= hidden_field_tag :category, "Seafood"  %>
          <input class="restaurant-card-pic" type="image" name="Seafood" src="https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Fine dining", restaurants_path(category: "Seafood") %>
        </form>

        <form class="restaurant-category" action="/restaurants" method="GET">
          <%= hidden_field_tag :category, "Vegan"  %>
          <input class="restaurant-card-pic" type="image" name="Vegan" src="https://images.unsplash.com/photo-1485963631004-f2f00b1d6606?ixlib=rb-1.2.1&auto=format&fit=crop&w=1868&q=80" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Mediterranean", restaurants_path(category: "Vegan") %>
        </form>

        <form class="restaurant-category" action="/restaurants" method="GET">
          <input class="restaurant-card-pic" type="image" name="All" src="https://images.unsplash.com/photo-1516447071-1ed8f76407b4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Street Food", restaurants_path %>
        </form>

        <form class="restaurant-category" action="/restaurants" method="GET">
          <%= hidden_field_tag :category, "Italian"  %>
          <input class="restaurant-card-pic" type="image" name="Italian" src="https://images.unsplash.com/photo-1543340713-1bf56d3d1b68?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1919&q=80" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Turkish",restaurants_path(category: "Italian") %>
        </form>

        <form class="restaurant-category" action="/restaurants" method="GET">
          <%= hidden_field_tag :category, "Japanese"  %>
          <input class="restaurant-card-pic" type="image"  name="Japanese" src="https://images.unsplash.com/photo-1542528180-a1208c5169a5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1957&q=80" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Lebanese", restaurants_path(category: "Japanese") %>
        </form>

        <form class="restaurant-category" action="/restaurants" method="GET">
          <%= hidden_field_tag :category, "Seafood"  %>
          <input class="restaurant-card-pic" type="image" name="Seafood" src="https://images.unsplash.com/photo-1543573852-1a71a6ce19bc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Desserts", restaurants_path(category: "Seafood") %>
        </form>

        <form class="restaurant-category" action="/restaurants" method="GET">
          <%= hidden_field_tag :category, "Vegan"  %>
          <input class="restaurant-card-pic" type="image" name="Vegan" src="https://images.unsplash.com/photo-1565355857989-333dff0b3dc8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1951&q=80" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Thai", restaurants_path(category: "Vegan") %>
        </form>

app/views/restaurants/index.html.erb
<div class="container">

  <div class="restaurant-whole-page">
    <h2 class="restaurant-index-heading">Choose A Restaurant</h2>

    <h4>Filter by cuisine:</h4>

    <div class="wrapper", style="overflow-x: hidden">
      <i class="fas fa-chevron-left fa-3x" id="carouselTriggerLeft"></i>
      <i class="fas fa-chevron-right fa-3x" id="carouselTriggerRight"></i>
      <div class="restaurant-category-cards">
        <%= render "restaurants-carousel" %>
      </div>
    </div>

  <hr>

  <div class="restaurant-grid-index-with-map">
    <div class="restaurant-index-cards">
      <% @restaurants.each do |restaurant| %>
        <div class="restaurant-index-card">
          <% if restaurant.photo.attached? %>
            <div class="restaurant-index-image text-center grid-photo">
              <%= link_to restaurant_path(restaurant) do %>
                <%= cl_image_tag restaurant.photo.key, height: 200, width: 300 %>
              <% end %>
            </div>

            <div class="restaurant-index-info text-left">
              <div class="resto-name-review">
                <h3 id="resto-name"><%= link_to restaurant.name, restaurant_path(restaurant)  %></h3>
              </div>
                  <div id="resto-review">
                    <% rand(4...5).times do %>

                      <i class="fas fa-star"></i>
                    <% end %>
                  </div>
                <p><%= restaurant.description %></p>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <div id="map" class="index-map"
      style="height: 600px !important;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>
</div>

  <script>
    const grid = document.querySelector('.restaurant-category-cards')
    const left = document.getElementById('carouselTriggerLeft')
    const right = document.getElementById('carouselTriggerRight')
    right.addEventListener('click', (event) => {
      // Spread syntax, turns a DOMTokenList into an array
      if ([...grid.classList].includes('middle-position')) {
        grid.classList.add('right-position')
      } else {
        grid.classList.add('middle-position')
      }
    })
    left.addEventListener('click', (event) => {
      if ([...grid.classList].includes('right-position')) {
        grid.classList.remove('right-position')
      } else {
        grid.classList.remove('middle-position')
      }
    })
  </script>

app/views/restaurants/show.html.erb
<div class="container">
  <h2 class="restaurant-header m-5 text-center"><%= @restaurant.name %></h2>

<!-- div of restaurant-image and map -->
  <div class="restaurant-image mb-5">
    <div>
      <%= cl_image_tag @restaurant.photo.key, height: 500, width: 750 %>
    </div>

    <div class="restaurant-information">
      <h4 class="pb-4"><%= @restaurant.name %></h4>
        <ol>
          <li>
            <b>Address: </b><%= @restaurant.address %>
          </li>
          <li>
            <b>Opening hours: </b> <%= @restaurant.open_hour %>
          </li>
          <li>
            <b>Contact number: </b><%= @restaurant.phone_number %>
          </li>
          <li>
            <b>Category: </b><%= @restaurant.category %>
          </li>
          <li>
            <b>Budget : </b>
            <% @average_price = @restaurant.price/40 %>
            <% if @average_price == 0 %>
              <i class="fas fa-pound-sign"></i>
            <% else %>
              <% @average_price.times do %>
                <i class="fas fa-pound-sign"></i>
              <% end %>
            <% end %>
          </li>
        </ol>
        <%= render partial: "shared/restaurant_modal" %>
    </div>
<div class="show-middle-container">
    <div>
      <h5>Reviews</h5>
    <% if @restaurant.reviews.blank? %>
      Be the first one to leave a comment for <%= @restaurant.name %>
    <% else %>
      <% @restaurant.reviews.each do |review|%>
  <!--    <div class="border ratings-table"> -->
        <div class="mb-4">
          <p>
            <% if review.user.profile_photo.attached?%>
              <%= cl_image_tag review.user.profile_photo.key,class: "avatar"%>
            <% else %>
              <i class="fas fa-user"></i>
            <% end %>
            <span class="ml-2 mr-4"><%= review.user.user_name %></span>
            <% review.rating.times do %>
              <i class="fas fa-star"></i>
            <% end %>
            <% (5 - review.rating).times do %>
              <i class="far fa-star"></i>
            <% end %>
            <% if review.user == current_user %>
              <%= link_to review_path(review), method: :delete do %>
                <i class="fas fa-trash ml-4 review-bin"></i>
              <% end %>
            <% end %>
          </p>
          <p><%= review.content %></p>
        </div>
      <% end %>
    <% end %>
</div>

    <div>
    <hr>
     <p class="pt-4"><%= @restaurant.details_description %></p>
   </div>
  </div>
<!-- class for information  -->

  <div class="show-ratings mb-4">
    <h3 class="mb-4">Leave a review</h3>
     <div class="restaurant-review-form mb-5">
    <%= simple_form_for [@review] do |f| %>
      <%= f.input :rating, collection: 1..5  %>
      <%= f.input :content %>
      <%= f.input :restaurant_id, as: :hidden, input_html: { value:  @restaurant.id  }%>
      <%= f.submit class: "btn btn-dark" %>
    <% end %>
  </div>


  </div>

  <div id="map" class="show-map"
      style="height: 500px !important;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
<!--   </div> -->
<br>

<br>


  </div>
</div>