config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :activities, only:[ :index, :show ]
  resources :restaurants, only:[:index, :show]
  resources :reviews, only: [:create, :destroy]
  resources :bookings, only: [:index,:show,:update,:destroy]

  get "category", to: "pages#category", as: :category
  patch "add_restaurant", to: "bookings#add_restaurant", as: :add_restaurant
  patch "add_activity", to: "bookings#add_activity", as: :add_activity

  post "activity_redirect_booking", to: "bookings#activity_redirect_booking", as: :activity_redirect_booking
  post "restaurant_redirect_booking", to: "bookings#restaurant_redirect_booking", as: :restaurant_redirect_booking
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :bookings
  has_many :reviews
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    if params[:category]
      @activities = Activity.where(category: params[:category]).geocoded
      @markers = @activities.map do |activity|
        {
          lat: activity.latitude,
          lng: activity.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { activity: activity })
        }
      end

    else
      @activities = Activity.geocoded
      @markers = @activities.map do |activity|
        {
          lat: activity.latitude,
          lng: activity.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { activity: activity })
        }
      end
    # @categories = @activities.pluck(:category)
    # @categories_unique = @categories.uniq
    end
  end


  def show
    @activity = Activity.find(params[:id])
     @markers =
      {
        lat: @activity.latitude,
        lng: @activity.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { activity: @activity })
      }
    @review = Review.new
  end
end

app/views/activities/_activities-carousel.html.erb
<form class="activity-category" action="/activities" method="GET">
          <input class="activity-card-pic" type="image" value="All" name="museum" src="https://res.cloudinary.com/dhhorrhuq/image/upload/v1583500331/priscilla-du-preez-gGmSBAps6K0-unsplash_zp4pto.jpg" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "All", activities_path%>
        </form>

        <form class="activity-category" action="/activities" method="GET">
          <%= hidden_field_tag :category, "Sport"  %>
          <input class="activity-card-pic" type="image" value="Sport" name="sport" src="https://res.cloudinary.com/dhhorrhuq/image/upload/v1583500350/bruno-nascimento-PHIgYUGQPvU-unsplash_sxrbge.jpg" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Sport", activities_path(category: "Sport") %>
        </form>

        <form class="activity-category" action="/activities" method="GET">
          <%= hidden_field_tag :category, "Market"  %>
          <input class="activity-card-pic" type="image" value="Market" name="market" src="https://res.cloudinary.com/dhhorrhuq/image/upload/v1583358057/jordan-madrid-NvdscovENOY-unsplash_vztthl.jpg" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Market", activities_path(category: "Market") %>
        </form>

        <form class="activity-category" action="/activities" method="GET">
          <%= hidden_field_tag :category, "Museum"  %>
          <input class="activity-card-pic" type="image" name="Museum" src="https://res.cloudinary.com/dhhorrhuq/image/upload/v1583357559/category_muserum_jbirey.jpg" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Museum", activities_path(category: "Museum") %>
        </form>

        <form class="activity-category" action="/activities" method="GET">
          <%= hidden_field_tag :category, "Outdoor"  %>
          <input class="activity-card-pic" type="image" name="Theatre" src="https://res.cloudinary.com/dhhorrhuq/image/upload/v1583499938/category_act_outdoor_qxtayc.jpg" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Outdoor", activities_path(category: "Outdoor") %>
        </form>

        <form class="activity-category" action="/activities" method="GET">
          <input class="activity-card-pic" type="image" value="All" name="Cooking" src="https://images.unsplash.com/photo-1556910103-1c02745aae4d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Cooking", activities_path%>
        </form>

        <form class="activity-category" action="/activities" method="GET">
          <%= hidden_field_tag :category, "Sport"  %>
          <input class="activity-card-pic" type="image" value="Sport" name="sport" src="https://images.unsplash.com/photo-1544824082-9b29e2f106af?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2849&q=80" border="0" alt="Submit" style="width: 200px; height: 120px" />
          <%= link_to "Motor Sports", activities_path(category: "Sport") %>
        </form>

        <form class="activity-category" action="/activities" method="GET">
          <%= hidden_field_tag :category, "Market"  %>
          <input class="activity-card-pic" type="image" value="Market" name="market" src="https://images.unsplash.com/photo-1562329265-95a6d7a83440?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2764&q=80" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Theatre", activities_path(category: "Market") %>
        </form>

        <form class="activity-category" action="/activities" method="GET">
          <%= hidden_field_tag :category, "Museum"  %>
          <input class="activity-card-pic" type="image" name="Movies" src="https://images.unsplash.com/photo-1527979809431-ea3d5c0c01c9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1984&q=80" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Movies", activities_path(category: "Museum") %>
        </form>

        <form class="activity-category" action="/activities" method="GET">
          <%= hidden_field_tag :category, "Outdoor"  %>
          <input class="activity-card-pic" type="image" name="concerts" src="https://images.unsplash.com/photo-1523973740062-18e700e8da35?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2000&q=80" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Concerts", activities_path(category: "Concerts") %>
        </form>

        <form class="activity-category" action="/activities" method="GET">
          <input class="activity-card-pic" type="image" value="All" name="music" src="https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Live Music", activities_path%>
        </form>

        <form class="activity-category" action="/activities" method="GET">
          <%= hidden_field_tag :category, "Sport"  %>
          <input class="activity-card-pic" type="image" value="Sport" name="dance" src="https://images.unsplash.com/photo-1531747056595-07f6cbbe10ad?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" border="0" alt="Submit" style="width: 200px; height: 120px" />
          <%= link_to "Dancing", activities_path(category: "Sport") %>
        </form>

        <form class="activity-category" action="/activities" method="GET">
          <%= hidden_field_tag :category, "Market"  %>
          <input class="activity-card-pic" type="image" value="Market" name="market" src="https://images.unsplash.com/photo-1441974231531-c6227db76b6e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1951&q=80" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Nature", activities_path(category: "Market") %>
        </form>

        <form class="activity-category" action="/activities" method="GET">
          <%= hidden_field_tag :category, "Museum"  %>
          <input class="activity-card-pic" type="image" name="Museum" src="https://images.unsplash.com/photo-1507146426996-ef05306b995a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Animals", activities_path(category: "Museum") %>
        </form>

        <form class="activity-category" action="/activities" method="GET">
          <%= hidden_field_tag :category, "Outdoor"  %>
          <input class="activity-card-pic" type="image" name="Theatre" src="https://images.unsplash.com/photo-1511882150382-421056c89033?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1951&q=80" border="0" alt="Submit" style="width: 200px; height: 120px" />
        <%= link_to "Arcade", activities_path(category: "Outdoor") %>

        </form>

app/views/activities/_info_window.html.erb
<div>
  <h4 id="map-activity-name"><%= link_to activity.name, activity_path(activity) %></h4>
  <p><%= activity.address %></p>
</div>

app/views/activities/index.html.erb
<div class="container">
  <div class="activity-whole-page">
    <h2 class="activity-index-heading">Choose An Activity</h2>

    <h4>Filter by category:</h4>

    <!-- arrows for wrapper fontawesome -->
      <div class="wrapper", style=" overflow-x: hidden">
        <i class="fas fas fa-chevron-left fa-3x" id="carouselTriggerLeft"></i>
        <i class="fas fa-chevron-right fa-3x" id="carouselTriggerRight"></i>
        <div class="activity-category-cards">
          <%= render "activities-carousel" %>
        </div>
    </div>


  <hr>

  <div class="activity-grid-index-with-map">
    <div class="activity-index-cards">
      <% @activities.each do |activity| %>
        <div class="activity-index-card">
          <% if activity.photo.attached? %>
            <div class="activity-index-image text-center grid-photo">
              <%= link_to activity_path(activity) do %>
                <%= cl_image_tag activity.photo.key, height: 200, width: 300 %>
              <% end %>
            </div>

            <div class="activity-index-info text-left">
              <div class="activity-name-review">
                <h3 id="activity-name"><%= link_to activity.name, activity_path(activity)  %></h3>
              </div>
                <div id="activity-review">
                  <% rand(4..5).times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                  </div>
                <p><%= activity.description %></p>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <div id="map" class="index-map"
      style="height: 600px !important; "
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>
</div>

<!-- DO NOT DELETE following code here
 -->  <%#= link_to "Museum", category(category: Museum) %>
  <%# @categories_unique.each do |category| %>
     <!--  <form id="category" action="/category" method="GET"> -->
      <%#= hidden_field_tag :category, category  %>
      <!-- <input type="image" value="#{category}" src="https://jekyllcodex.org/uploads/grumpycat.jpg" border="0" alt="Submit" style="width: 50px;" />
<%#= submit_tag  "#{category}"  %> -->
    <!-- </form>-->
  <%# end %>

  <script>
    document.addEventListener('turbolinks:load', () => {
      const grid = document.querySelector('.activity-category-cards')
      const left = document.getElementById('carouselTriggerLeft')
      const right = document.getElementById('carouselTriggerRight')
      right.addEventListener('click', (event) => {
        // Spread syntax, turns a DOMTokenList into an array
        if ([...grid.classList].includes('middle-position')) {
          grid.classList.add('right-position')
        } else {
          grid.classList.add('middle-position')
        }
      })
      left.addEventListener('click', (event) => {
        if ([...grid.classList].includes('right-position')) {
          grid.classList.remove('right-position')
        } else {
          grid.classList.remove('middle-position')
        }
      })
    })

  </script>

app/views/activities/show.html.erb
<div class="container">
  <h2 class="activity-header m-5 text-center"><%= @activity.name %></h2>

<!-- div of activity-image -->
  <div class="activity-image mb-5">
    <div><%= cl_image_tag @activity.photo.key, height: 500, width: 750 %></div>
    <!-- class for information  -->
      <div class="activity-information">
        <h4 class="pb-4"><%= @activity.name %></h4>
          <ol>
            <li>
              <b>Address: </b><%= @activity.address %>
            </li>
            <li>
              <b>Opening hours: </b> <%= @activity.open_hour %>
            </li>
            <li>
              <b>Contact number: </b><%= @activity.phone_number %>
            </li>
            <li>
              <b>Category: </b><%= @activity.category %>
            </li>
            <li>
              <b>Budget : </b>
              <% @average_price = @activity.price/40 %>
              <% if @average_price == 0 %>
                <i class="fas fa-pound-sign"></i>
              <% else %>
                <% @average_price.times do %>
                  <i class="fas fa-pound-sign"></i>
                <% end %>
              <% end %>
            </li>
          </ol>
          <%= render partial: "shared/activity_modal" %>
  </div>

  <div class="show-middle-container">
    <div>
      <h5>Reviews</h5>
     <% if @activity.reviews.blank? %>
      Be the first one to leave a comment for <%= @activity.name %>
    <% else %>
      <% @activity.reviews.each do |review|%>
  <!--       <div class="border ratings-table"> -->
      <div class="mb-4">
          <p>
            <% if review.user.profile_photo.attached?%>
              <%= cl_image_tag review.user.profile_photo.key,class: "avatar" %>
            <% else %>
              <i class="fas fa-user"></i>
            <% end %>
            <span class="ml-2 mr-4"><%= review.user.user_name %></span>
            <% review.rating.times do %>
              <i class="fas fa-star"></i>
            <% end %>
            <% (5 - review.rating).times do %>
              <i class="far fa-star"></i>
            <% end %>
            <% if review.user == current_user %>
              <%=  link_to review_path(review), method: :delete do %>
                  <i class="fas fa-trash ml-4 review-bin"></i>
              <% end %>
            <% end %>
          </p>
          <p><%= review.content %></p>
        </div>
      <% end %>
    <% end %>
    </div>

    <div>
      <hr>
      <p class="pt-4"><%= @activity.details_description %></p>
    </div>
  </div>

  <div class="show-ratings mb-4">
    <h4 class="mb-4">Leave a review</h4>
    <div class="activity-review-form mb-5">
      <%= simple_form_for [@review] do |f| %>
        <%= f.input :rating, collection: 1..5 %>
        <%= f.input :content %>
        <%= f.input :activity_id, as: :hidden, input_html: { value:  @activity.id }%>
        <%= f.submit class: "btn btn-dark" %>
      <% end %>
    </div>


  </div>

  <div id="map" class="show-map"
      style="height: 500px !important;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
<!--   </div> -->
<br>

<br>


</div>
</div>